### ISSUE TITLE
method not found error.

### ISSUE THREAD

**Issue by sanjeevkrn** [m-wu/GaitLib#1]
I am getting below error with your code. Can you share the native code for spectral-analyses
java.lang.UnsatisfiedLinkError: Native method not found: SpectralAnalyses.fasperArray:(FF[F[F[F[FI)[[F

**Comment by aibiluv** [comment]
Hi, I also couldn't pass SpectralAnalyses.fasperArray(....) method. The c code isn't added to the project. Have you gotten any luck with it?

**Comment by m-wu** [comment]
Hey guys, sorry for the long overdue reply (I haven't been working on this project for a while).

In case you are still interested, the C code for Spectral Analyses has been added to the repo. To compile it, a number of files from [Numerical Recipes](http://www.nr.com/aboutNR3code.html) are required to be placed under `/jni/nr/`:

```
nr/realft.c
nr/fasper.c
nr/nrutil.c
nr/four1.c
nr/spread.c
nr/avevar.c
nr/gasdev.c
nr/ran1.c
```

These files cannot be included in this repo because of license restriction. I was under the impression that the library was able to run with the compiled binary instead of the C code, but it seems that wasn't the case.
